// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: buckets.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBucket = `-- name: CreateBucket :one
INSERT INTO buckets (user_id, name, starting_balance)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, starting_balance, archived_at, created_at
`

type CreateBucketParams struct {
	UserID          uuid.UUID `json:"user_id"`
	Name            string    `json:"name"`
	StartingBalance int64     `json:"starting_balance"`
}

func (q *Queries) CreateBucket(ctx context.Context, arg CreateBucketParams) (Bucket, error) {
	row := q.db.QueryRow(ctx, createBucket, arg.UserID, arg.Name, arg.StartingBalance)
	var i Bucket
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.StartingBalance,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getBucket = `-- name: GetBucket :one
SELECT id, user_id, name, starting_balance, archived_at, created_at
FROM buckets
WHERE id = $1 AND user_id = $2
`

type GetBucketParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetBucket(ctx context.Context, arg GetBucketParams) (Bucket, error) {
	row := q.db.QueryRow(ctx, getBucket, arg.ID, arg.UserID)
	var i Bucket
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.StartingBalance,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listBuckets = `-- name: ListBuckets :many
SELECT id, user_id, name, starting_balance, archived_at, created_at
FROM buckets
WHERE user_id = $1 AND archived_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListBuckets(ctx context.Context, userID uuid.UUID) ([]Bucket, error) {
	rows, err := q.db.Query(ctx, listBuckets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bucket{}
	for rows.Next() {
		var i Bucket
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.StartingBalance,
			&i.ArchivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBucket = `-- name: UpdateBucket :one
UPDATE buckets
SET name = $3, archived_at = $4
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, starting_balance, archived_at, created_at
`

type UpdateBucketParams struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Name       string             `json:"name"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

func (q *Queries) UpdateBucket(ctx context.Context, arg UpdateBucketParams) (Bucket, error) {
	row := q.db.QueryRow(ctx, updateBucket,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.ArchivedAt,
	)
	var i Bucket
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.StartingBalance,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}
