// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Bucket struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	Name            string             `json:"name"`
	StartingBalance int64              `json:"starting_balance"`
	ArchivedAt      pgtype.Timestamptz `json:"archived_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Person struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Name       string             `json:"name"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Reminder struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	Title          string             `json:"title"`
	Amount         *int64             `json:"amount"`
	DefaultType    string             `json:"default_type"`
	RecurrenceType string             `json:"recurrence_type"`
	RecurrenceDay  *int32             `json:"recurrence_day"`
	NextDueAt      pgtype.Timestamptz `json:"next_due_at"`
	LinkedBucketID pgtype.UUID        `json:"linked_bucket_id"`
	LinkedPersonID pgtype.UUID        `json:"linked_person_id"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ReminderTag struct {
	ReminderID uuid.UUID `json:"reminder_id"`
	TagID      uuid.UUID `json:"tag_id"`
}

type Tag struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Name       string             `json:"name"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Transaction struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	Type         string             `json:"type"`
	Amount       int64              `json:"amount"`
	FromBucketID pgtype.UUID        `json:"from_bucket_id"`
	ToBucketID   pgtype.UUID        `json:"to_bucket_id"`
	PersonID     pgtype.UUID        `json:"person_id"`
	Note         string             `json:"note"`
	OccurredAt   pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ReversesID   pgtype.UUID        `json:"reverses_id"`
}

type TransactionTag struct {
	TransactionID uuid.UUID `json:"transaction_id"`
	TagID         uuid.UUID `json:"tag_id"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Name         *string            `json:"name"`
	Phone        *string            `json:"phone"`
}
