// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: people.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPerson = `-- name: CreatePerson :one
INSERT INTO people (user_id, name)
VALUES ($1, $2)
RETURNING id, user_id, name, archived_at, created_at
`

type CreatePersonParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, createPerson, arg.UserID, arg.Name)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPerson = `-- name: GetPerson :one
SELECT id, user_id, name, archived_at, created_at
FROM people
WHERE id = $1 AND user_id = $2
`

type GetPersonParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetPerson(ctx context.Context, arg GetPersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, getPerson, arg.ID, arg.UserID)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPeople = `-- name: ListPeople :many
SELECT id, user_id, name, archived_at, created_at
FROM people
WHERE user_id = $1 AND archived_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListPeople(ctx context.Context, userID uuid.UUID) ([]Person, error) {
	rows, err := q.db.Query(ctx, listPeople, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Person{}
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.ArchivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePerson = `-- name: UpdatePerson :one
UPDATE people
SET name = $3, archived_at = $4
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, archived_at, created_at
`

type UpdatePersonParams struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Name       string             `json:"name"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

func (q *Queries) UpdatePerson(ctx context.Context, arg UpdatePersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, updatePerson,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.ArchivedAt,
	)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}
