// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reminders.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addReminderTag = `-- name: AddReminderTag :exec
INSERT INTO reminder_tags (reminder_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddReminderTagParams struct {
	ReminderID uuid.UUID `json:"reminder_id"`
	TagID      uuid.UUID `json:"tag_id"`
}

func (q *Queries) AddReminderTag(ctx context.Context, arg AddReminderTagParams) error {
	_, err := q.db.Exec(ctx, addReminderTag, arg.ReminderID, arg.TagID)
	return err
}

const createReminder = `-- name: CreateReminder :one
INSERT INTO reminders (
    user_id, title, amount, default_type, recurrence_type, recurrence_day,
    next_due_at, linked_bucket_id, linked_person_id, status
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, 'active')
RETURNING id, user_id, title, amount, default_type, recurrence_type, recurrence_day,
          next_due_at, linked_bucket_id, linked_person_id, status, created_at
`

type CreateReminderParams struct {
	UserID         uuid.UUID          `json:"user_id"`
	Title          string             `json:"title"`
	Amount         *int64             `json:"amount"`
	DefaultType    string             `json:"default_type"`
	RecurrenceType string             `json:"recurrence_type"`
	RecurrenceDay  *int32             `json:"recurrence_day"`
	NextDueAt      pgtype.Timestamptz `json:"next_due_at"`
	LinkedBucketID pgtype.UUID        `json:"linked_bucket_id"`
	LinkedPersonID pgtype.UUID        `json:"linked_person_id"`
}

func (q *Queries) CreateReminder(ctx context.Context, arg CreateReminderParams) (Reminder, error) {
	row := q.db.QueryRow(ctx, createReminder,
		arg.UserID,
		arg.Title,
		arg.Amount,
		arg.DefaultType,
		arg.RecurrenceType,
		arg.RecurrenceDay,
		arg.NextDueAt,
		arg.LinkedBucketID,
		arg.LinkedPersonID,
	)
	var i Reminder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Amount,
		&i.DefaultType,
		&i.RecurrenceType,
		&i.RecurrenceDay,
		&i.NextDueAt,
		&i.LinkedBucketID,
		&i.LinkedPersonID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteReminderTags = `-- name: DeleteReminderTags :exec
DELETE FROM reminder_tags WHERE reminder_id = $1
`

func (q *Queries) DeleteReminderTags(ctx context.Context, reminderID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteReminderTags, reminderID)
	return err
}

const getReminder = `-- name: GetReminder :one
SELECT id, user_id, title, amount, default_type, recurrence_type, recurrence_day,
       next_due_at, linked_bucket_id, linked_person_id, status, created_at
FROM reminders
WHERE id = $1 AND user_id = $2
`

type GetReminderParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetReminder(ctx context.Context, arg GetReminderParams) (Reminder, error) {
	row := q.db.QueryRow(ctx, getReminder, arg.ID, arg.UserID)
	var i Reminder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Amount,
		&i.DefaultType,
		&i.RecurrenceType,
		&i.RecurrenceDay,
		&i.NextDueAt,
		&i.LinkedBucketID,
		&i.LinkedPersonID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getReminderTags = `-- name: GetReminderTags :many
SELECT tg.id, tg.user_id, tg.name, tg.archived_at, tg.created_at
FROM tags tg
JOIN reminder_tags rt ON rt.tag_id = tg.id
WHERE rt.reminder_id = $1
`

func (q *Queries) GetReminderTags(ctx context.Context, reminderID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getReminderTags, reminderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.ArchivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReminders = `-- name: ListReminders :many
SELECT id, user_id, title, amount, default_type, recurrence_type, recurrence_day,
       next_due_at, linked_bucket_id, linked_person_id, status, created_at
FROM reminders
WHERE user_id = $1
  AND status = 'active'
  AND ($2::timestamptz IS NULL OR next_due_at <= $2)
ORDER BY next_due_at ASC
`

type ListRemindersParams struct {
	UserID  uuid.UUID          `json:"user_id"`
	Column2 pgtype.Timestamptz `json:"column_2"`
}

func (q *Queries) ListReminders(ctx context.Context, arg ListRemindersParams) ([]Reminder, error) {
	rows, err := q.db.Query(ctx, listReminders, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reminder{}
	for rows.Next() {
		var i Reminder
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Amount,
			&i.DefaultType,
			&i.RecurrenceType,
			&i.RecurrenceDay,
			&i.NextDueAt,
			&i.LinkedBucketID,
			&i.LinkedPersonID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReminder = `-- name: UpdateReminder :one
UPDATE reminders
SET title = $3,
    amount = $4,
    default_type = $5,
    recurrence_type = $6,
    recurrence_day = $7,
    next_due_at = $8,
    linked_bucket_id = $9,
    linked_person_id = $10,
    status = $11
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, amount, default_type, recurrence_type, recurrence_day,
          next_due_at, linked_bucket_id, linked_person_id, status, created_at
`

type UpdateReminderParams struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	Title          string             `json:"title"`
	Amount         *int64             `json:"amount"`
	DefaultType    string             `json:"default_type"`
	RecurrenceType string             `json:"recurrence_type"`
	RecurrenceDay  *int32             `json:"recurrence_day"`
	NextDueAt      pgtype.Timestamptz `json:"next_due_at"`
	LinkedBucketID pgtype.UUID        `json:"linked_bucket_id"`
	LinkedPersonID pgtype.UUID        `json:"linked_person_id"`
	Status         string             `json:"status"`
}

func (q *Queries) UpdateReminder(ctx context.Context, arg UpdateReminderParams) (Reminder, error) {
	row := q.db.QueryRow(ctx, updateReminder,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Amount,
		arg.DefaultType,
		arg.RecurrenceType,
		arg.RecurrenceDay,
		arg.NextDueAt,
		arg.LinkedBucketID,
		arg.LinkedPersonID,
		arg.Status,
	)
	var i Reminder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Amount,
		&i.DefaultType,
		&i.RecurrenceType,
		&i.RecurrenceDay,
		&i.NextDueAt,
		&i.LinkedBucketID,
		&i.LinkedPersonID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
