// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addTransactionTag = `-- name: AddTransactionTag :exec
INSERT INTO transaction_tags (transaction_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddTransactionTagParams struct {
	TransactionID uuid.UUID `json:"transaction_id"`
	TagID         uuid.UUID `json:"tag_id"`
}

func (q *Queries) AddTransactionTag(ctx context.Context, arg AddTransactionTagParams) error {
	_, err := q.db.Exec(ctx, addTransactionTag, arg.TransactionID, arg.TagID)
	return err
}

const bucketBalances = `-- name: BucketBalances :many
SELECT
    b.id AS bucket_id,
    b.name,
    CAST(b.starting_balance + COALESCE(
        SUM(CASE
            WHEN t.to_bucket_id = b.id THEN t.amount
            WHEN t.from_bucket_id = b.id THEN -t.amount
            ELSE 0
        END) FILTER (WHERE t.reverses_id IS NULL AND NOT EXISTS (
            SELECT 1 FROM transactions r WHERE r.reverses_id = t.id
        )),
    0) AS BIGINT) AS balance_paisa
FROM buckets b
LEFT JOIN transactions t ON (t.from_bucket_id = b.id OR t.to_bucket_id = b.id)
    AND t.user_id = $1
WHERE b.user_id = $1 AND b.archived_at IS NULL
GROUP BY b.id, b.name, b.starting_balance
ORDER BY b.created_at ASC
`

type BucketBalancesRow struct {
	BucketID     uuid.UUID `json:"bucket_id"`
	Name         string    `json:"name"`
	BalancePaisa int64     `json:"balance_paisa"`
}

func (q *Queries) BucketBalances(ctx context.Context, userID uuid.UUID) ([]BucketBalancesRow, error) {
	rows, err := q.db.Query(ctx, bucketBalances, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BucketBalancesRow{}
	for rows.Next() {
		var i BucketBalancesRow
		if err := rows.Scan(&i.BucketID, &i.Name, &i.BalancePaisa); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    user_id, type, amount, from_bucket_id, to_bucket_id,
    person_id, note, occurred_at, reverses_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, type, amount, from_bucket_id, to_bucket_id,
          person_id, note, occurred_at, created_at, reverses_id
`

type CreateTransactionParams struct {
	UserID       uuid.UUID          `json:"user_id"`
	Type         string             `json:"type"`
	Amount       int64              `json:"amount"`
	FromBucketID pgtype.UUID        `json:"from_bucket_id"`
	ToBucketID   pgtype.UUID        `json:"to_bucket_id"`
	PersonID     pgtype.UUID        `json:"person_id"`
	Note         string             `json:"note"`
	OccurredAt   pgtype.Timestamptz `json:"occurred_at"`
	ReversesID   pgtype.UUID        `json:"reverses_id"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.Type,
		arg.Amount,
		arg.FromBucketID,
		arg.ToBucketID,
		arg.PersonID,
		arg.Note,
		arg.OccurredAt,
		arg.ReversesID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Amount,
		&i.FromBucketID,
		&i.ToBucketID,
		&i.PersonID,
		&i.Note,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.ReversesID,
	)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, user_id, type, amount, from_bucket_id, to_bucket_id,
       person_id, note, occurred_at, created_at, reverses_id
FROM transactions
WHERE id = $1 AND user_id = $2
`

type GetTransactionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetTransaction(ctx context.Context, arg GetTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, arg.ID, arg.UserID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Amount,
		&i.FromBucketID,
		&i.ToBucketID,
		&i.PersonID,
		&i.Note,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.ReversesID,
	)
	return i, err
}

const getTransactionTags = `-- name: GetTransactionTags :many
SELECT tg.id, tg.user_id, tg.name, tg.archived_at, tg.created_at
FROM tags tg
JOIN transaction_tags tt ON tt.tag_id = tg.id
WHERE tt.transaction_id = $1
`

func (q *Queries) GetTransactionTags(ctx context.Context, transactionID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getTransactionTags, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.ArchivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isTransactionReversed = `-- name: IsTransactionReversed :one
SELECT EXISTS (
    SELECT 1 FROM transactions WHERE reverses_id = $1
) AS reversed
`

func (q *Queries) IsTransactionReversed(ctx context.Context, reversesID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isTransactionReversed, reversesID)
	var reversed bool
	err := row.Scan(&reversed)
	return reversed, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT t.id, t.user_id, t.type, t.amount, t.from_bucket_id, t.to_bucket_id,
       t.person_id, t.note, t.occurred_at, t.created_at, t.reverses_id
FROM transactions t
WHERE t.user_id = $1
  AND NOT EXISTS (
      SELECT 1 FROM transactions r WHERE r.reverses_id = t.id
  )
  AND t.reverses_id IS NULL
  AND ($2 = '' OR t.type = $2)
  AND ($3 = '00000000-0000-0000-0000-000000000000'::uuid OR t.from_bucket_id = $3 OR t.to_bucket_id = $3)
  AND ($4 = '00000000-0000-0000-0000-000000000000'::uuid OR t.person_id = $4)
  AND ($5::timestamptz IS NULL OR t.occurred_at >= $5)
  AND ($6::timestamptz IS NULL OR t.occurred_at <= $6)
  AND (
      $7 = '00000000-0000-0000-0000-000000000000'::uuid OR
      EXISTS (
          SELECT 1 FROM transaction_tags tt WHERE tt.transaction_id = t.id AND tt.tag_id = $7
      )
  )
  AND ($8::timestamptz IS NULL OR $9 = '00000000-0000-0000-0000-000000000000'::uuid OR (t.occurred_at, t.id) < ($8, $9))
ORDER BY t.occurred_at DESC, t.id DESC
LIMIT $10
`

type ListTransactionsParams struct {
	UserID  uuid.UUID          `json:"user_id"`
	Column2 interface{}        `json:"column_2"`
	Column3 interface{}        `json:"column_3"`
	Column4 interface{}        `json:"column_4"`
	Column5 pgtype.Timestamptz `json:"column_5"`
	Column6 pgtype.Timestamptz `json:"column_6"`
	Column7 interface{}        `json:"column_7"`
	Column8 pgtype.Timestamptz `json:"column_8"`
	Column9 interface{}        `json:"column_9"`
	Limit   int32              `json:"limit"`
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactions,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Amount,
			&i.FromBucketID,
			&i.ToBucketID,
			&i.PersonID,
			&i.Note,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.ReversesID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const monthlySummary = `-- name: MonthlySummary :one
SELECT
    CAST(COALESCE(SUM(t.amount) FILTER (WHERE t.type = 'income'), 0) AS BIGINT) AS total_income,
    CAST(COALESCE(SUM(t.amount) FILTER (WHERE t.type = 'expense'), 0) AS BIGINT) AS total_expense
FROM transactions t
WHERE t.user_id = $1
  AND t.occurred_at >= $2
  AND t.occurred_at < $3
  AND t.reverses_id IS NULL
  AND NOT EXISTS (SELECT 1 FROM transactions r WHERE r.reverses_id = t.id)
`

type MonthlySummaryParams struct {
	UserID       uuid.UUID          `json:"user_id"`
	OccurredAt   pgtype.Timestamptz `json:"occurred_at"`
	OccurredAt_2 pgtype.Timestamptz `json:"occurred_at_2"`
}

type MonthlySummaryRow struct {
	TotalIncome  int64 `json:"total_income"`
	TotalExpense int64 `json:"total_expense"`
}

func (q *Queries) MonthlySummary(ctx context.Context, arg MonthlySummaryParams) (MonthlySummaryRow, error) {
	row := q.db.QueryRow(ctx, monthlySummary, arg.UserID, arg.OccurredAt, arg.OccurredAt_2)
	var i MonthlySummaryRow
	err := row.Scan(&i.TotalIncome, &i.TotalExpense)
	return i, err
}

const personBalances = `-- name: PersonBalances :many
SELECT
    p.id AS person_id,
    p.name,
    CAST(COALESCE(
        SUM(CASE
            WHEN t.type IN ('loan_given', 'repayment_received') THEN t.amount
            WHEN t.type IN ('loan_taken', 'repayment_paid') THEN -t.amount
            ELSE 0
        END) FILTER (WHERE t.reverses_id IS NULL AND NOT EXISTS (
            SELECT 1 FROM transactions r WHERE r.reverses_id = t.id
        )),
    0) AS BIGINT) AS net_paisa
FROM people p
LEFT JOIN transactions t ON t.person_id = p.id AND t.user_id = $1
WHERE p.user_id = $1 AND p.archived_at IS NULL
GROUP BY p.id, p.name
ORDER BY p.created_at ASC
`

type PersonBalancesRow struct {
	PersonID uuid.UUID `json:"person_id"`
	Name     string    `json:"name"`
	NetPaisa int64     `json:"net_paisa"`
}

func (q *Queries) PersonBalances(ctx context.Context, userID uuid.UUID) ([]PersonBalancesRow, error) {
	rows, err := q.db.Query(ctx, personBalances, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PersonBalancesRow{}
	for rows.Next() {
		var i PersonBalancesRow
		if err := rows.Scan(&i.PersonID, &i.Name, &i.NetPaisa); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tagTotals = `-- name: TagTotals :many
SELECT
    tg.id AS tag_id,
    tg.name,
    CAST(COALESCE(
        SUM(t.amount) FILTER (WHERE t.reverses_id IS NULL AND NOT EXISTS (
            SELECT 1 FROM transactions r WHERE r.reverses_id = t.id
        )),
    0) AS BIGINT) AS total_paisa
FROM tags tg
JOIN transaction_tags tt ON tt.tag_id = tg.id
JOIN transactions t ON t.id = tt.transaction_id
    AND t.user_id = $1
    AND t.occurred_at >= $2
    AND t.occurred_at <= $3
    AND t.type = 'expense'
WHERE tg.user_id = $1 AND tg.archived_at IS NULL
GROUP BY tg.id, tg.name
ORDER BY total_paisa DESC
`

type TagTotalsParams struct {
	UserID       uuid.UUID          `json:"user_id"`
	OccurredAt   pgtype.Timestamptz `json:"occurred_at"`
	OccurredAt_2 pgtype.Timestamptz `json:"occurred_at_2"`
}

type TagTotalsRow struct {
	TagID      uuid.UUID `json:"tag_id"`
	Name       string    `json:"name"`
	TotalPaisa int64     `json:"total_paisa"`
}

func (q *Queries) TagTotals(ctx context.Context, arg TagTotalsParams) ([]TagTotalsRow, error) {
	rows, err := q.db.Query(ctx, tagTotals, arg.UserID, arg.OccurredAt, arg.OccurredAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TagTotalsRow{}
	for rows.Next() {
		var i TagTotalsRow
		if err := rows.Scan(&i.TagID, &i.Name, &i.TotalPaisa); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
